### PR TITLE
fix: suggested changes done

### PR DESCRIPTION
**Pull request by Shaharyar-saleem**
1. Account Modal Copy Address
2. Disclaimer update color
3. Hover effects on buttons
4. Feeless -> TaxFree
5. Magnify Bottom Logo
6. Add all social icons to the bottom
7. Remove console log
8. center on the bottom

### CODE REVIEW

**Review by bobachef — CHANGES_REQUESTED** [review]
Awesome PR! Just 2 things

1. `Tax Free` instead of `TaxFree` and make sure to use the right caps. `TaxFreely Swappable BUSD` should be `Tax Free BUSD Available`
2. After user copies account change tooltip to `Copied` for a second before changing back so they know their action has successfully occured.

**Comment by Shaharyar-saleem** [comment]
> Awesome PR! Just 2 things
> 
> 1. `Tax Free` instead of `TaxFree` and make sure to use the right caps. `TaxFreely Swappable BUSD` should be `Tax Free BUSD Amount`
> 2. After user copies account change tooltip to `Copied` for a second before changing back so they know their action has successfully occured.

done both points

**Comment by Shaharyar-saleem** [comment]
@bobachef Tablet and mobile version of the pazz-app is yet to complete.

**Review by bobachef — APPROVED** [review]
still not 100% but i'm gonna merge it so we can have smaller prs

**Pull request merged**
